### PR TITLE
Fixed issue with this.minimap.onMouseWheel() is not a function

### LINKED ISSUE #3: Fixed issue with this.minimap.onMouseWheel() is not a function
https://github.com/atom-minimap/minimap/pull/641

### PR DESCRIPTION
**Pull request by aminya**
https://github.com/atom-minimap/minimap/pull/641

Fixes https://github.com/atom-ide-community/minimap/issues/3

### CODE REVIEW

File: lib/minimap-element.js [hunk 1]
```diff
@@ -475,7 +475,7 @@ class MinimapElement {
 
   /**
    * Creates the content of the MinimapElement and attaches the mouse control
-   * event listeners.
+   * event listeners.
```
Comment (aminya) [inline lib/minimap-element.js:478]:
```suggestion
   * event listeners.
```
